### ISSUE TITLE
MPI

### ISSUE THREAD

**Issue by rhl-** [conan-io/wishlist#1]
OpenMPI/MPICH
https://www.open-mpi.org/
https://www.mpich.org/downloads/

OS X, Linux, on x86 and x86_64

**Comment by memsharded** [comment]
Hi! Sorry, I forgot to add to the Readme, I am doing it now. Could you please specify the platforms, OS, compilers, you would need this package?

**Comment by rhl-** [comment]
i thought the idea for conan was to abstract all of these details away. most modern operating systems provide these packages (homebrew on OS/X, repostories on every distribution of linux). Obviously both clang and gcc. 

MPI is a dependency for boost-mpi (part of boost), so, i'm surprised it isn't already packaged..

**Comment by memsharded** [comment]
Maybe the scope of conan is not properly explained. Conan is not is an "automated" translator or abstraction over packages already existing in OS package managers (though that would be a great project idea, in fact, it has already been considered). Certainly, a conan package recipe can be perfectly used for that task, instead of running source() to retrieve source code and build() with typical build commands inside, it can run an invocation to the respective OS package manager.

Conan is not designed to replace the OS package managers either, and it is perfectly right to depend on packages provided by those managers, as well as on packages living in conan. If the Boost packages already existing in those package managers work well, just use them. Conan helps when those packages are not existing in OS package managers (which can be a huge use case if coding in windows, which has a very large market share for C and C++ developers), or for your own libraries, if you have large (portable between different OS and distros) projects composed by many libraries and you don't want to create .deb, .rpm, .pkg, .msi, etc... for different platforms.

Let's say that it is a tool for library developers, if I develop an useful and portable C++ library, lets say with CMake as build system, I can create a conanfile.py recipe for it in a few minutes and make it available instantaneously to be consumed from any OS. I can also immediately upload binaries created locally, or create them with CI (travis, appveyor) and share them also instantaneously. The effort to make packages for different OS and distros is typically much, much larger.

So, with conan, package creators would typically need to test the packages, and it is better if they have input of the intended usage. Many projects have builds that change with the OS: there are projects that build (the same project) with makefiles in linux and CMake in Win. Other have variable dependencies depending on the OS too (e.g. the ZMQ package might add the wsock32 lib in windows, but obviously not in linux). Also library names might change between different OS builds... The job of conan is to provide the tools to abstract all these things, but the package creator typically has to translate the settings to concrete build commands.

MPI could be an optional dependency for Boost, so that could explain why it has not been added yet. Up to my knowledge, the current existing package does not support Boost.Python either. I hope this wishlist helps to improve these things.

Thanks very much for your feedback, please tell me if you want to further discuss any of these things. Cheers.

**Comment by rhl-** [comment]
I'm not sure I follow you.  

First of all, the purpose of this issue is to suggest adding MPI as a package in conan, for the whole matrix of available compilers, OSes, and pronunciations of tomato possible.

Secondly, in response, you've said a lot of things. Lets discuss some of them.

1: > Conan is not is an "automated" translator or abstraction over packages already existing in OS package managers 

2: > Conan is not designed to replace the OS package managers either, and it is perfectly right to depend on packages provided by those managers, as well as on packages living in conan. If the Boost packages already existing in those package managers work well,  just use them.

Ok, but conan is a package manager for C/C++. The definition of a package manager, is, to automate the process of installing/removing software. Many such C/C++ packages are exist already in OS package managers. If you don't want to duplicate them (as suggested in 2), then in contradiction to 1, you need to paper over them for the user.  

If you suggest that you expect people to handwrite logic for going out to the system to apt-get or yum or brew, for whatever package it is that you do not want (or do not have) in conan, then, you aren't helping me solve my dependency problems, your just repackaging them in a new system. Namely, I can already write a per OS shell script and just call the right one from CMake. How is conan making this easier? Also, it doesn't completely solve the problem, when, for example, the person doing the compiling, doesn't have root access, they probably can't use the installer on most operating systems.

So I would say  based on what I have heard the scope of conan is not yet well defined, and you should think a bit harder about it, and try to actually encapsulate the real dependency issues here. 

I might recommend trying your best to get as many packages into Conan, and not restricting the build matrix of OSes at all.

**Comment by memsharded** [comment]
I was trying to say that conan is not opinionated on what the users should do, and try to let the users decide what packages they want from which origins without interfering. Of course we will try our best to provide as many packages as possible in conan, and we do not want to restrict at all the build matrix, just the opposite. Please note that, for example, (even if it might not be perfect) our current Boost package recipe has more than 160 binary variants in it, that is quite a large build matrix.

It was more kind of a pragmatic hint for potential contributors newcomers. This wishlist is open to anyone to contribute, and some users might not be able or not want to provide or test the packages in multiple OSs. Even if you write a proper conanfile.py recipe, lets say for latest OpenCV, and try to account for portability, if you only write it and test in windows, it is unlikely that it will work for linux.

We will try to provide contributors with support on how to setup multi OS CI with travis and appveyor, but we don't want to discourage any contribution, even if they only provide support for 1 OS. If requesters suggest their preferred platforms, that might help contributors to focus first on certain platforms testing, it is just a hint to improve their first steps and maximize initial progress.

Thanks very much again for your suggestions, we will seriously take them into account to try to improve conan.

**Comment by rhl-** [comment]
Thats all fine. I don't have the resources to provide a travis/appveyor build for most packages. That would have to be provided to me.

**Comment by SSE4** [comment]
bincrafters have OpenMPI package:
https://bintray.com/bincrafters/public-conan/openmpi%3Abincrafters
MS MPI is coming soon

**Comment by SSE4** [comment]
Microsoft MPI is also available
https://bintray.com/bincrafters/public-conan/msmpi%3Abincrafters

**Comment by Croydon** [comment]
This is not an atomic issue

I would suggest to split it, if other mpi's are wanted too

If only openMPI is relevant we can close in favour of https://github.com/conan-io/conan-center-index/issues/1858

**Comment by Croydon** [comment]
Openmpi is now available https://conan.io/center/openmpi (https://github.com/conan-io/conan-center-index/pull/4482)

I suggest to close this issue. If other MPIs are desired, I recommend opening atomic issues here: https://github.com/conan-io/conan-center-index/issues
