### ISSUE TITLE
GTK+

### ISSUE THREAD

**Issue by computerquip** [conan-io/wishlist#15]
GTK+ is a toolkit for creating graphic interfaces. It's very common and featured on Linux but can be used for both MacOSX and Windows, to a lesser degree. It has various dependencies which can be particularly difficult to setup for some. 

Website: http://www.gtk.org/
Building Guide: https://developer.gnome.org/gtk3/stable/gtk-building.html

It's not particularly friendly or common on Windows or MacOSX. I'd prioritize Linux toolchains if anything.

**Comment by liberforce** [comment]
For Windows, using Visual Studio would make more sense. GTK+ 3 is already available on Windows through the [MSYS2](http://www.msys2.org/) project. Those packages are built using gcc. This makes it impossible to use the Visual Studio debugger due to debug symbols being different being compilers, so what is really missing (and out of the scope of MSYS2) would be to have GTK+ 3 packages built with Visual Studio.

GTK+ 4 is also in preparation and uses the [Meson](http://mesonbuild.com/) build system, which should make it easier to build on Windows.

**Comment by liberforce** [comment]
Seems getting GTK+ 3 will be easier, on Windows too, as the Meson port will be backported:

> In addition to what was mentioned there, we also plan to backport the new event controllers, to make porting to GTK+ 4 easier. We will also add meson build support to help with Windows builds.

Source: https://blog.gtk.org/2018/07/12/a-report-from-the-guadec-gtk-bof/

**Comment by SSE4** [comment]
this one would be a complex beast (from https://gitlab.gnome.org/GNOME/gtk):
```
In order to build GTK you will need:

a C99 compatible compiler
Python 3
Meson
Ninja

You will also need various dependencies, based on the platform you are
building for:

GLib
GdkPixbuf
GObject-Introspection
Cairo
Pango
Epoxy
Graphene
ATK
Xkb-common

If you are building the X11 backend, you will also need:

Xlib, and the following X extensions:

xrandr
xrender
xi
xext
xfixes
xcursor
xdamage
xcomposite


atk-bridge-2.0

If you are building the Wayland backend, you will also need:

Wayland-client
Wayland-protocols
Wayland-cursor
Wayland-EGL
```

**Comment by Croydon** [comment]
Still missing = ❌
Exists, but not in CCI = ⌛
In CCI = ✔️

___________

In order to build GTK you will need:

(✔️ a C99 compatible compiler )
(✔️ Python 3 )
✔️ Meson
✔️ Ninja

You will also need various dependencies, based on the platform you are
building for:

✔️ GLib 
✔️ GdkPixbuf
❌ GObject-Introspection
✔️ Cairo
✔️ Pango
✔️ Epoxy
✔️ Graphene
✔️ ATK
✔️ Xkb-common

(all of the X11 libs are in the `xorg/system` package)
If you are building the X11 backend, you will also need:
✔️ Xlib
and the following X extensions:
✔️ xrandr
✔️ xrender
✔️ xi
✔️ xext
✔️ xfixes
✔️ xcursor
✔️ xdamage
✔️ xcomposite


❌ atk-bridge-2.0

If you are building the Wayland backend, you will also need:

❌ Wayland-client
❌ Wayland-protocols
❌ Wayland-cursor
❌ Wayland-EGL

**Comment by KingKili** [comment]
If anyone is working on the gtk+ port I'd be also willing to help.

**Comment by ericLemanissier** [comment]
I'm not sure that missing dependencies should prevent us from packaging libraries(gtk). We can start by using system versions of the dependencies in the first place and migrate them as they are packaged later. The other alternative for the user is to use system version of the library (gtk), which involves even more system libraries, so it feels worse to me.

**Comment by compiaffe** [comment]
@Croydon We have conan packaged a few of these and have them available on our own artifactory (Which might not scale to too many users, but we have to see)
The conan sources are here:
https://gitlab.com/aivero/public/conan

I believe we have 
- Glib
- GObject-Introspection
- Cairo
- Pango
- Epoxy

Have a look here: https://conan.aa.aivero.dev/artifactory/webapp/#/artifacts/browse/tree/General/aivero-public


FYI @noverby

**Comment by ericLemanissier** [comment]
Do your recipes support windows ?

**Comment by compiaffe** [comment]
@ericLemanissier We don't yet. So far all is for Linux. There will be Windows support at some point, but not for at least the next few months.

**Comment by noverby** [comment]
@ericLemanissier Not yet, but it is on our roadmap.

**Comment by Croydon** [comment]
> I'm not sure that missing dependencies should prevent us from packaging libraries(gtk)

Agreed, it doesn't prevent us from starting, but this issue is about getting it into Conan Center and for that it is a blocker

**Comment by Croydon** [comment]
> @Croydon We have conan packaged a few of these and have them available on our own artifactory

Awesome!

However, none of those repository seem to have LICENSE files, so we can't re-use any of that right now 🙂

**Comment by overby-me** [comment]
> However, none of those repository seem to have LICENSE files, so we can't re-use any of that right now slightly_smiling_face

@Croydon @compiaffe Now all the repositories contain a MIT license file

**Comment by compiaffe** [comment]
@Croydon if you happen to add windows support we get the chance ourselves, please drop a comment here. (or do a MR/PR on our repos ;) )

**Comment by ericLemanissier** [comment]
the effort is ongoing here https://github.com/bincrafters/conan-gtk

**Comment by feliwir** [comment]
What's currently still stoping this from happening? IIRC i did pango and some other deps aswell, so i'd be willing to contribute again.

**Comment by ericLemanissier** [comment]
Linux is working fine, but windows does not because of a meson limitation. I guess we could release a version on the stable channel. Can you try it?
EDIT: the windows issues I mentioned are listed in https://github.com/bincrafters/community/issues/1150

**Comment by morevnaproject** [comment]
Is it possible to have older gtk (i.e. 3.22.x) and with MinGW?

**Comment by ericLemanissier** [comment]
sure, all the contributions are welcome :wink:

**Comment by ericLemanissier** [comment]
I just released gtk 3.24.18 on the stable channel. If any of you could provide feedback on the linux or macos gtk package, I'd be glad to hear it.
3.24.20 has a [bug](https://gitlab.gnome.org/GNOME/gtk/-/issues/2669) preventing the build with meson. While checking this I realized that maybe all the windows issues would be solved by using the configure script instead of meson. I'll try it in few days.

**Comment by liberforce** [comment]
...or you could just add the missing file and retry. Autotools on Windows have always been a pain in the ass. Meson isn't perfect, but the support backported to 3.x has been a good move, and 4.x will use Meson by default which will give you the same workflow. So IMHO there should be more than a missing file in the released package to justify reverting to using the autotools.

**Comment by ericLemanissier** [comment]
I was not clear enough, the missing file is preventing to release gtk/3.24.20 on all platforms. gtk/3.24.18 is working ok on linux and macos. You can make a PR on https://github.com/bincrafters/conan-gtk if you cannot live with gtk/3.24.18 until 3.24.22 is released upstream.
The issue I have with windows are listed in https://github.com/bincrafters/community/issues/1150, if you want to help.

EDIT: I largely prefer meson over autotools, but comments like [this](https://gitlab.gnome.org/GNOME/gtk/-/issues/2698#note_789647) make me consider autotools again

**Comment by liberforce** [comment]
I understand, Matthias Clasen's comment sound like autotools is to be prefered, but Emmanuele Bassi looks more inclined to make Meson work. They're both GTK+ maintainers, I'm not sure they're all aligned there. So ebassi would probably more willing to help on Meson issues.

**Comment by Croydon** [comment]
I updated the dependency list above: https://github.com/conan-io/wishlist/issues/15#issuecomment-573321098

We made progress but still quite some work to do

I'm not sure what parts of Wayland are covered by our `wayland/system` package 

There is also some activity going on here: https://github.com/conan-io/conan-center-index/pull/2749

**Comment by ericLemanissier** [comment]
This time,  this issue can be closed https://conan.io/center/gtk?version=3.24.24
