### ISSUE TITLE
opengl support (GLFW and GLEW)

### ISSUE THREAD

**Issue by qiukeren** [conan-io/wishlist#21]
Wish the package here?

<del>Wish a opengl~</del>

<del>We all know what it is ~</del>

So this issue is reopened in favor of glfw and glew.

glfw is cute and import for most opengl developers.

Want a glfw and glew here.

**Comment by memsharded** [comment]
Hi! Yes, we know. But GL is already available in OS, isn't it. E.g. the OpenGL32 lib comes bundled with VS, not needed to build a package for it. Linux distros have mesa, but being it non cross-platform, I think there is little interest in creating a package for it, and better use the distro bundled lib. Also, the OpenGL is portable and absolutely stable, packages make more sense also for more evolving libs. As a hint, you could use conan ``system_requirements()`` to run an ``apt-get install`` in your system. Otherwise, could you provide a pointer to the source code to be packaged? Also specific version and hints to cross-platform building such source code? Thank you!

**Comment by arkloot** [comment]
I think, a library like GLEW is what @qiukeren might be interested in:

http://glew.sourceforge.net/

**Comment by qiukeren** [comment]
@arkloot GLEW and GLFW are both required.

**Comment by memsharded** [comment]
+1 for GLFW. I have used it and is great

**Comment by GavinNL** [comment]
I created this tested in on Linux Mint 18.  Compiles from souce on linux, pulls the prebuilt binaries for windows. I haven't tested in Mac since I have no idea how to compile on Mac. If anyone can fork and submit pull requests, that would be awesome!

https://github.com/GavinNL/conan_glfw

**Comment by phobos2077** [comment]
OpenGL library would be nice. Right now there is only vcpkg version which only works for MVSC. I want to use Conan as a package manager for cross-platform project, but now it's only useful for Windows because some packages are missing (opengl being one of them).

**Comment by memsharded** [comment]
But you want OpenGL or GLFW, GLEW libraries? OpenGL is usually at the system level.
I did some work to provide support for GLFW for Win/OSX for the user GavinNL here: https://github.com/memsharded/conan_glfw, but never found time to finish it. Please tell me a bit more about your project, maybe you can help testing and maturing the GLFW conan package, if it is the one you need. Thanks!

**Comment by phobos2077** [comment]
@memsharded , thanks for response.
I have following packages currently set up for project in conanfile.txt:

```
zlib/1.2.11@lasote/stable
SDL2/2.0.5@lasote/stable
SDL2_image/2.0.1@lasote/stable
SDL2_mixer/2.0.1@a_teammate/testing
opengl/0.0-3.0@lasote/vcpkg
glew/2.0.0@lasote/vcpkg
glm/0.9.7.6@dlarudgus20/stable
```

But the problem is that this only works for Windows+MSVC. vcpkg packages don't work on Linux obviously, so I tried replacing glew and opengl. But didn't find any Opengl packages.

> OpenGL is usually at the system level.

What do you mean by that?

PS: I use cmake on this project.

**Comment by memsharded** [comment]
> OpenGL

OpenGL is a library that comes installed with the system. Visual Studio brings it. Linux will typically install it with the display drivers. And many times, an optimized version of it is installed with the graphic card drivers. So the libraries we need as developers are most times (unless you are a very low level graphics developer) the higher level wrappers like GLFW and similar libraries.

**Comment by a-teammate** [comment]
I think a distinct package would be really helpful.

Different packages need GL and typically all either assume they are there, or get them in a hacky way for just a specific platform.
What would be great is an all-in-one package for each distro:

in VS it adds "OpenGL32"
for debian based it installs mesa-dev via apt
for arch, it installs mesa-dev via ...
or maybe one can get the mesa dev headers otherwise, idk.

(the problem here is that mesa might be installed, but mesa-dev often isn't)

Until then my suggestion to any package needing opengl would be:
just don't check for it, don't try anything fancy to get these dev headers, just assume them (and install them in the travis scripts if necessary)

**Comment by SSE4** [comment]
bincrafters has glfw package:
https://bintray.com/bincrafters/public-conan/glfw%3Abincrafters

**Comment by SSE4** [comment]
bincrafters have glew as well
https://bintray.com/bincrafters/public-conan/glew%3Abincrafters

**Comment by danimtb** [comment]
Please @SSE4 send us inclusion request for those packages into conan-center! Will try to push them forward

**Comment by SSE4** [comment]
@danimtb sent

**Comment by SSE4** [comment]
glew & glfw are now in conan center
