### ISSUE TITLE
Add Conan.io to chocolatey for windows

### ISSUE THREAD

**Issue by solvingJ** [conan-io/wishlist#53]
Chocolatey is a package manager for windows (like yum or apt-get).  Would be great to add conan to it.

**Comment by memsharded** [comment]
You mean, being able to install conan client app (different from conan.io) with chocolatey? 
We strongly recommend to install conan with python/pip, even if we provide a Win installer, that doesn't require python installed:

- It is very simple to setup: installing Python in win is very simple, and conan with pip even more. The whole process can be done in a couple of minutes
- The Win installer might have some limitations, due to the embedding of the python interpreter in the creation of the executable done by pyinstaller. Chocolatey might suffer the same limitation.

**Comment by solvingJ** [comment]
Yes, exactly (installing the conan client app via chocolatey). BTW, conan is great and I think it's a big step forward. 


Getting setup to publish packages on Chocolatey is not trivial matter and takes a bit of work. You have to work out a fully scripted installation, update, and uninstallation of your product through the MSI.  It will be understandable if the Conan.io dev team does not have time to go through all this on behalf of the windows user community.  That would be an acceptable reason to close and reject this feature request.  

_Note: Perhaps a community member can go through all this for you, as I've seen several other open source projects such as cmake, vim, mingw, etc; all of which were published on chocolatey by others (not the project owners)._  

However, I would just provide the following feedback:

- It's not reasonable to suggest to developers who happen to use windows, that in order to get the package manager they have to install a completely different language, no matter how easy it is. Yes, python is awesome and I have it, it's just not reasonable to expect a C++ guy to install it because you wrote the installer in python. 
- I'm not familiar with what limitations the Win installer for conan client "Might Have" (if you are thinking of any specific ones, please call them out and I'll be happy to look into them).  However, based on the installer I saw, it's almost certainly good enough to go on Chocolatey.  

Again, I totally understand if it's just a matter of time and availability, but I don't believe that there's a valid technical reason to NOT put it on chocolatey.

**Comment by memsharded** [comment]
Yes, exactly that, we are overwhelmed with development of core features, so it is not that we don't want this,  just that we don't know chocolatey, so we prefer that some chocolatey expert would create this installer (as is the case of the Arch Linux conan installer, already created and maintained by one community member).

In any case, we do NOT require to install python. The provided Windows installer in the downloads page is self contained, it will install just the application with everything bundled, no need to install python. 

Basically the main limitation of the windows (and other self contained installers) installer is that it is created with pyinstaller, which transforms the python code into an executable that also bundles the python interpreter. The problem is when someone wants to use a python standard library feature that is not used by the conan codebase. Pyinstaller just bundle the used python features. Recently we had a bug report that a simple ``import glob`` failed with the conan app created with pyinstaller. We fixed that in pyinstaller code, but this might happen again for other libs. And we cannot just import every python standard library by default (I think this might also have a bad effect on performance of the app)

**Comment by solvingJ** [comment]
Ok, that's good to know.  Perhaps put a note up on the site that lets the community know you're looking for help with this.  GL!

**Comment by solvingJ** [comment]
I'm dropping a note in the chocolatey gitter asking if anyone is interested.

**Comment by ferventcoder** [comment]
Reference: https://gitter.im/chocolatey/choco?at=5852ecd4fb22792b3b6ac756

I think there may be disagreement on trivialness by folks who have done packaging. Choco comes with `choco new pkgid`, and it generates most of the packaging for you.

You can choose to go with 

* MSI installer (embedded or not)
* Runtime software binaries (embedded or unzipped)

Either way you can also decide for the latter option to take a dependency on the python package.


Going the MSI is downloaded at runtime route looks like this:

~~~powershell
$ErrorActionPreference = 'Stop';

$packageName  = 'Conan-Package-Manager'
$toolsDir     = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"

$packageArgs = @{
  packageName   = $packageName
  softwareName  = 'Conan Package Manager*'
  file          = $fileLocation
  fileType      = 'exe'
  silentArgs    = "/VERYSILENT /NORESTART /RESTARTEXITCODE=3010 /SP- /SUPPRESSMSGBOXES /CLOSEAPPLICATIONS /FORCECLOSEAPPLICATIONS /NOICONS"
  validExitCodes= @(0,3010)
  destination   = $toolsDir
  
  url           = 'https://github.com/conan-io/conan/releases/download/0.17.0/conan-win_0_17_0.exe'checksum      = '4A0F90530813A8CE3E5A8F2B5B2E27CC5432C42AEEEE4131132D946D5B9F5AF4'
  checksumType  = 'sha256'
}

Install-ChocolateyPackage @packageArgs 
~~~

But one could go a different route where Python is installed as a dependency and the binaries are just included in the package itself. Then

**Comment by ferventcoder** [comment]
I always prefer runtime binaries embedded in the package - that allows Chocolatey to work as a package manager rather than a software manager, working with Programs and Features.

**Comment by ferventcoder** [comment]
I'm not sure why there is a thought that it is non-trivial to do Chocolatey packaging. Compared to other platforms, it is insanely easy, although we still need to provide some help to get fpm working with Chocolatey.

**Comment by ferventcoder** [comment]
In the case here, I would suggest two packages - conan.install and conan.portable.

**Comment by ferventcoder** [comment]
Conan looks pretty cool by the way!

**Comment by ferventcoder** [comment]
I added Conan to the request for package list - https://github.com/chocolatey/chocolatey-package-requests/issues/28

**Comment by ferventcoder** [comment]
Updated my comments at https://github.com/conan-io/wishlist/issues/53#issuecomment-267419665

**Comment by ferventcoder** [comment]
I also forgot to mention, you should also be able to call  `choco install conan --source python` now.

**Comment by memsharded** [comment]
Thanks very much @solvingJ @ferventcoder (Rob),

We haven't used choco ourselves, but I know some users that use it to install dev tools in Win, and they like it very much, so it is good news that it is not such a difficult task. Cheers!
