### ISSUE TITLE
Apache log4cxx/0.10.0

### ISSUE THREAD

**Issue by CodingSpiderFox** [conan-io/wishlist#56]
It would be great to have apache log4cxx available on conan.

Apache log4cxx is a logging framework for C++ (see https://logging.apache.org/log4cxx/latest_stable/)

Latests version is 0.10.0.
Desired platforms are Windows Visual Studio 2010 - 2015 (vc10, vc11, vc12, vc14) and Linux gcc

**Comment by monsdar** [comment]
log4cxx is not actively maintained anymore (release 0.10.0 is from 2008-04-03). The issue is that without modifications all your desired Windows compilers are not supported (I think the last supported version is 2008, vc90). I'm not sure about the supported gcc versions. You need to make modifications to the code to make it compile.

If you have the possibility I would suggest to use another logging framework. A good log4j-like implementation for C++ is [log4cplus](https://github.com/log4cplus/log4cplus) in my opinion. Version 1.x works for all your desired platforms, version 2.x builds on top of C++11, so VS2015 is required.

There's already a conan package für log4cplus available, though it needs some love:
https://www.conan.io/source/log4cplus/1.2.0-RC4/Kretsch0/testing

I've heard that there are some forks of log4cxx that enable building with newer compilers, but I'm not sure how thorougly they've been tested.

**Comment by CodingSpiderFox** [comment]
I agree that it is quite old and not maintained actively

But for legacy projects, I would fint it quite useful to have it available via conan.io

**Comment by jgsogo** [comment]
I'm working on it, @CodingSpiderFox, also for legacy projects :sob:  Follow [this repo](https://github.com/jgsogo/conan-apache-log4cxx). My current plan is to clone the original project and create a CMake for it, I've went through many different errors trying to use the provided `.dsw` in Windows (btw, linux more or less is working)

**Comment by jgsogo** [comment]
And, also for reference, there is still one hero here https://github.com/apache/logging-log4cxx that maintains the official version https://git-wip-us.apache.org/repos/asf?p=logging-log4cxx.git;a=summary

**Comment by jgsogo** [comment]
It is starting to compile in windows and linux, although I'm having problems with linkage. If anyone wants to help they will be very welcome. PR in [the repo](https://github.com/jgsogo/conan-apache-log4cxx) are open, but if you are working to work in something it will be better to open first an issue to coordinate efforts. Thanks!
